"""add unique constraints to author and tag names

Revision ID: 0b4cb0eea37e
Revises: 08cbc7ff70a8
Create Date: 2026-08-16 12:25:25.136168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4cb0eea37e'
down_revision: Union[str, Sequence[str], None] = '08cbc7ff70a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=True)
    op.create_unique_constraint('uq_tag_name_type', 'tags', ['name', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tag_name_type', 'tags', type_='unique')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    # ### end Alembic commands ###
